### ISSUE TITLE
Split apart server name & owner

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/master-server#1]
So for instance @minnesotags could be listed as owner while his server name remains tuffkidtech

Could also eventually be good info to list in-game if the owner name matches a user/player name

Edit: On the other hand maybe "Name" should just become "Owner" to keep it simple (with the URL more or less being the name)

**Comment by msteiger** [comment]
Sounds reasonable. I will add the owner column to the table.

**Comment by msteiger** [comment]
Fixed by 73701564e4b1.

**Comment by Cervator** [comment]
Cool :-)
